// frule-console-js/src/components/tree/component/Tree.vue
<template>
    <ul style='padding-left: 20px'>
        <TreeItem data={data} dispatch={dispatch} expandLevel={this.props.expandLevel}
                  draggable={draggable} />
    </ul>
</template>
<script>
    import '../css/tree.css';
    import '../../../css/iconfont.css';

    export default {
        name: 'Tree',
        props: ['draggable']
    }
</script>

// frule-console-js/src/components/tree/component/Tree.jsx
/**
 * Created by Jacky.gao on 2016/5/23.
 */
import TreeItem from './TreeItem.jsx';
import React, {Component, PropTypes} from 'react';
import {connect} from 'react-redux';

class Tree extends Component {
    render() {
        const {data, dispatch, draggable} = this.props;
        if (data) {
            return (
                <ul style={{paddingLeft: '20px'}}>
                    <TreeItem data={data} dispatch={dispatch} expandLevel={this.props.expandLevel}
                              draggable={draggable}/>
                </ul>
            );
        } else {
            return (<ul></ul>);
        }
    }
};
Tree.defaultProps = {expandLevel: 3};

function selector(state) {
    let data = state.data;
    return {data};
};
export default connect(selector)(Tree);
